spring:
  datasource:
    hikari:
      connection-timeout: 30000
      max-lifetime: 600000
      pool-name: XCodeHikariCP
      minimum-idle: 1
      maximum-pool-size: 2
      idle-timeout: 30000
    dynamic:
      primary: basecenter #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      datasource:
        # 主库数据源
        basecenter:
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          url: jdbc:p6spy:oracle:thin:@172.31.0.45:1521/dghb
          username: basecenter
          password: basecenter
        # 是否开启sql日志输出，生产环境建议关闭，有性能损耗
      p6spy: true